name: VampireUHC
version: '1.0.0'
main: fr.vampireuhc.VampireUHC
api-version: '26.2'
description: UHC a mecanique de marqueurs/auras inspire du Loup-Garou UHC
author: Olruix (VRAM-RAM on github)

commands:
  vuhc:
    description: Main command for VampireUHC plugin
    usage: /vuhc <start [sec]|stop|reset|spectate <joueur>|status|who|aura|marquer|trancher|proteger|voter|switch|role>

permissions:
  vuhc.admin:
    description: Permet de lancer, arrêter et réinitialiser la partie
    default: op
